# **Install Library**

In [36]:
# Install library

!pip install transformers
!pip install faiss-cpu
!pip install pandas
!pip install numpy
!pip install torch
!pip install streamlit
!pip install scikit-learn

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.0.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.25.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.5.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (1.3.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.28.1)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.24.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (4.15.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (0.16.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (0.1.2)
Requirement already satisfied: faiss-cpu in /usr/local/lib/python3.12/dist-packages (1.13.2)
Requirement already satisfied: numpy<3.0,>=1.25.0 in /usr/local/lib/python3.12/dist-packages (from faiss-cpu) (2.0.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from faiss-cpu) (26.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (2.10.0+cu128)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch) (3.25.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch) (2025.3.0)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch) (1.4.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch) (3.0.3)
Requirement already satisfied: streamlit in /usr/local/lib/python3.12/dist-packages (1.55.0)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (1.9.0)
Requirement already satisfied: cachetools<8,>=5.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.2.6)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (8.3.1)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /usr/local/lib/python3.12/dist-packages (from streamlit) (3.1.46)
Requirement already satisfied: numpy<3,>=1.23 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.0.2)
Requirement already satisfied: packaging>=20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (26.0)
Requirement already satisfied: pandas<3,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.2.2)
Requirement already satisfied: pillow<13,>=7.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (11.3.0)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.9.1)
Requirement already satisfied: protobuf<7,>=3.20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.29.6)
Requirement already satisfied: pyarrow>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (18.1.0)
Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.32.4)
Requirement already satisfied: tenacity<10,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (9.1.4)
Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.10.2)
Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.5.1)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (4.15.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.0.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (4.26.0)
Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2.17.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<3,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3,>=1.4.0->streamlit) (2025.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2026.2.25)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.2)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.30.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas<3,>=1.4.0->streamlit) (1.17.0)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (2.0.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)

# **Download Datasets**

In [37]:
#@title import kebutuhan library
import pandas as pd
import re
import torch
import faiss
import numpy as np
import os

In [38]:
if os.path.exists('data/sample_train.csv'):
    print("Menggunakan data lokal")
    df_train = pd.read_csv('data/sample_train.csv')
    df_valid = pd.read_csv('data/sample_valid.csv')
    df_test  = pd.read_csv('data/sample_test.csv')
else:
    print("Menggunakan data dari Github")
    train_url = "https://raw.githubusercontent.com/IndoNLP/indonlu/master/dataset/smsa_doc-sentiment-prosa/train_preprocess.tsv"
    valid_url = "https://raw.githubusercontent.com/IndoNLP/indonlu/master/dataset/smsa_doc-sentiment-prosa/valid_preprocess.tsv"
    test_url  = "https://raw.githubusercontent.com/IndoNLP/indonlu/master/dataset/smsa_doc-sentiment-prosa/test_preprocess.tsv"
    df_train = pd.read_csv(train_url, sep='\t', header=None, names=['text', 'label'])
    df_valid = pd.read_csv(valid_url, sep='\t', header=None, names=['text', 'label'])
    df_test  = pd.read_csv(test_url,  sep='\t', header=None, names=['text', 'label'])

Menggunakan data lokal

# **Exploratory Data Analysis (EDA)**

In [39]:
#@title show the data

def showdata(df_train, df_valid, df_test):
  for name, df in [("train", df_train), ("valid", df_valid), ("test", df_test)]:
    print(f"\n{name}")
    print(f"{display(df)}")
showdata(df_train, df_valid, df_test)

train

                                                  text     label
0    warung ini dimiliki oleh pengusaha pabrik tahu...  positive
1    mohon ulama lurus dan k212 mmbri hujjah partai...   neutral
2    lokasi strategis di jalan sumatera bandung tem...  positive
3    betapa bahagia nya diri ini saat unboxing pake...  positive
4    duh jadi mahasiswa jangan sombong dong kasih k...  negative
..                                                 ...       ...
97                         biar besok jadi anggota dpr   neutral
98   tokohtokoh penggerak gerakan partai pki indone...   neutral
99   gus mus bela dan doakan menteri susi pudjiastu...   neutral
100                          sudah di revisi om dengan   neutral
101  berita indonesia perdagangan bei ditutup presi...   neutral

[102 rows x 2 columns]

None

valid

                                                  text     label
0    meski masa kampanye sudah selesai bukan berati...   neutral
1                                           tidak enak  negative
2    restoran ini menawarkan makanan sunda kami mem...  positive
3    lokasi di alun alun masakan padang ini cukup t...  positive
4    betapa bejad kader gerindra yang anggota dprd ...  negative
..                                                 ...       ...
97   dedi mulyadi dan ridwan kamil dianggap kepala ...   neutral
98   11 kamera 3 kamera tetap 1 kamera depan dan 1 ...   neutral
99   sby penasaran hingga akhirnya mempertanyakan r...   neutral
100  arkeolog mesir temukan spinx baru di kuil kom ...   neutral
101  sby serahkan rekomendasi ke rai mantra sudiker...   neutral

[102 rows x 2 columns]

None

test

                                                  text     label
0    kemarin gue datang ke tempat makan baru yang a...  negative
1    kayak nya sih gue tidak akan mau balik lagi ke...  negative
2    kalau dipikirpikir sebenarnya tidak ada yang b...  negative
3    ini pertama kalinya gua ke bank buat ngurusin ...  negative
4    waktu sampai dengan gue pernah disuruh ibu lat...  negative
..                                                 ...       ...
97   hari ini periode submission xpresound telah di...   neutral
98   informasi tambahan bahwa untuk pembayaran rp 2...   neutral
99   sebentar lagi asian games 2018 dimulai nih cob...   neutral
100  pagi ini pemkab pemalang melalui menyelenggara...   neutral
101  kemnaker ri menyelenggarakan pameran kesempata...   neutral

[102 rows x 2 columns]

None

In [40]:
#@title null check

def nullcheck(df_train, df_valid, df_test):
  for name, df in [("train", df_train), ("valid", df_valid), ("test", df_test)]:
    print(f"{name} = {df.isnull().sum().sum()} null values")
nullcheck(df_train, df_valid, df_test)

train = 0 null values
valid = 0 null values
test = 0 null values

In [41]:
#@title label check

def label_check(df_train, df_valid, df_test):
  for name, df in [("train", df_train), ("valid", df_valid), ("test", df_test)]:
    print(f"\n{name}")
    print(df["label"].value_counts())
label_check(df_train, df_valid, df_test)

train
label
positive    34
neutral     34
negative    34
Name: count, dtype: int64

valid
label
neutral     34
negative    34
positive    34
Name: count, dtype: int64

test
label
negative    34
positive    34
neutral     34
Name: count, dtype: int64

In [42]:
#@title avarage length of text

def avglen_check(df_train, df_valid, df_test):
    for name, df in [("train", df_train), ("valid", df_valid), ("test", df_test)]:
        avg = df['text'].str.len().mean()
        print(f"{name} = rata-rata panjang teks: {avg:.1f} karakter")
avglen_check(df_train, df_valid, df_test)

train = rata-rata panjang teks: 146.5 karakter
valid = rata-rata panjang teks: 141.2 karakter
test = rata-rata panjang teks: 192.6 karakter

# **Preprocessing**

In [43]:
"""
Dataset SmSA dipreprocess oleh IndoNLU
namun saya akan tetap menerapkan preprocessing terlebih dahulu
untuk memastikan data konsisten
"""
def preprocess(text):
    text = text.lower()
    text = re.sub(r'http\S+', '', text)
    text = re.sub(r'[^a-zA-Z0-9\s]', '', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text
df_train['text'] = df_train['text'].apply(preprocess)
df_valid['text'] = df_valid['text'].apply(preprocess)
df_test['text']  = df_test['text'].apply(preprocess)

samples = df_train['text'].sample(7, random_state=55).tolist()
for text in samples:
  print("\nSebelum:", text)
  print("Sesudah:", preprocess(text))

Sebelum: pdip sebut ridwan kamil menang karena berbaju merah
Sesudah: pdip sebut ridwan kamil menang karena berbaju merah

Sebelum: pengalaman yang cukup seru makan tanpa alas piring tapi hanya dengan alas daun makin nikmat makanan sunda yang sangat bervariatif dan cukup enak tips nya jangan terbawa emosi dan kalap memesan dan memilih semua makanan yang disediakan biasanya kalap kalau sudah melihat makanan macammacam begitu pilih seperlunya
Sesudah: pengalaman yang cukup seru makan tanpa alas piring tapi hanya dengan alas daun makin nikmat makanan sunda yang sangat bervariatif dan cukup enak tips nya jangan terbawa emosi dan kalap memesan dan memilih semua makanan yang disediakan biasanya kalap kalau sudah melihat makanan macammacam begitu pilih seperlunya

Sebelum: sudah di revisi om dengan
Sesudah: sudah di revisi om dengan

Sebelum: biar besok jadi anggota dpr
Sesudah: biar besok jadi anggota dpr

Sebelum: kebakaran hutan di sumbing meluas
Sesudah: kebakaran hutan di sumbing meluas

Sebelum: akhir tahun lalu saya dan keluarga berjalan ke daerah lembang dan tidak sengaja mampir makan di resto ini suasana nya nyaman pelayanan juga ramah dan berlebihan ala kami puas makanan yang di sajikan standar seperti makanan di restoran pada umum nya tetapi yang membuat berbeda adalah sambal stroberi yang yummy dan bikin ketagihan di sana selain bisa makan kita juga bisa sambil memetik lanjutan
Sesudah: akhir tahun lalu saya dan keluarga berjalan ke daerah lembang dan tidak sengaja mampir makan di resto ini suasana nya nyaman pelayanan juga ramah dan berlebihan ala kami puas makanan yang di sajikan standar seperti makanan di restoran pada umum nya tetapi yang membuat berbeda adalah sambal stroberi yang yummy dan bikin ketagihan di sana selain bisa makan kita juga bisa sambil memetik lanjutan

Sebelum: gus mus bela dan doakan menteri susi pudjiastuti via
Sesudah: gus mus bela dan doakan menteri susi pudjiastuti via

# **Tokenisasi & Embedding**

In [44]:
from transformers import BertTokenizer, AutoModel

tokenizer = BertTokenizer.from_pretrained("indobenchmark/indobert-base-p2")
model = AutoModel.from_pretrained("indobenchmark/indobert-base-p2")
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = model.to(device)

def embedding(text):
  # proses tokenisasi teks
  input = tokenizer(text, return_tensors="pt", truncation=True, max_length=128, padding=True)
  input = {k: v.to(device) for k, v in input.items()}

  # proses dengan model
  with torch.no_grad():
    outputs = model(**input)

  # mengambil representasi vektor (CLS token)
  embedding = outputs.last_hidden_state[:, 0, :].squeeze().cpu().numpy()
  return embedding

#testing
test_embedding = embedding("saya")
print("Ukuran embedding:", test_embedding.shape)

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Ukuran embedding: (768,)

# **FAISS INDEX**

In [45]:
print("membuat embedding")
train_embedding = np.array([embedding(text) for text in df_train["text"]])
print("embedding berhasil dibuat!", train_embedding.shape)

membuat embedding
embedding berhasil dibuat! (102, 768)

In [46]:
#faiss index

dimension = 768
index = faiss.IndexFlatL2(dimension)

index.add(train_embedding)

print("Total vektor di FAISS:", index.ntotal)

#testing faiss

query = df_train['text'][0]
query_embedding = embedding(query).reshape(1, -1)

distances, indices = index.search(query_embedding, k=3)

print("Query:", query)
print("\nKalimat paling mirip:")
for i, idx in enumerate(indices[0]):
    print(f"{i+1}. {df_train['text'][idx]} (jarak: {distances[0][i]:.4f})")

#simpan faiss index

faiss.write_index(index, "smsa_faiss.index")
print("\nFAISS index berhasil disimpan!")

Total vektor di FAISS: 102
Query: warung ini dimiliki oleh pengusaha pabrik tahu yang sudah puluhan tahun terkenal membuat tahu putih di bandung tahu berkualitas dipadu keahlian memasak dipadu kretivitas jadilah warung yang menyajikan menu utama berbahan tahu ditambah menu umum lain seperti ayam semuanya selera indonesia harga cukup terjangkau jangan lewatkan tahu bletoka nya tidak kalah dengan yang asli dari tegal

Kalimat paling mirip:
1. warung ini dimiliki oleh pengusaha pabrik tahu yang sudah puluhan tahun terkenal membuat tahu putih di bandung tahu berkualitas dipadu keahlian memasak dipadu kretivitas jadilah warung yang menyajikan menu utama berbahan tahu ditambah menu umum lain seperti ayam semuanya selera indonesia harga cukup terjangkau jangan lewatkan tahu bletoka nya tidak kalah dengan yang asli dari tegal (jarak: 0.0000)
2. rasa bakso cuanki dan batagor cukup selalu ramai pengunjung buka sekitar jam 10 pagi dari jalan riau menuju jalan a yani ada sisi kiri jalan sekitar jalan anggrek harga per porsi sekitar rp 14 000 datanglah lebih awal karena selalu ramai pengunjung (jarak: 230.5743)
3. tempat steak di bandung sejak lama dari zaman setiabudi sampai sekarang buka cabang di riau tempat di riau ini lebih besar parkiran juga tidak sulit seperti di setiabudi lokasi di tempat kuliner jalan riau porsi dan harga nya pas untuk ukuran steak untuk zoom non smoking nya nyaman (jarak: 230.8248)

FAISS index berhasil disimpan!

# **TRAINING**

In [47]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.preprocessing import LabelEncoder

#membuat embedding "valid"
valid_embeddings = np.array([embedding(text) for text in df_valid['text']])
print(valid_embeddings.shape)
#membuat embedding "test"
test_embeddings = np.array([embedding(text) for text in df_test['text']])
print(test_embeddings.shape)

#encode label
le = LabelEncoder()
train_labels = le.fit_transform(df_train['label'])
valid_labels = le.transform(df_valid['label'])
test_labels  = le.transform(df_test['label'])
print("Label mapping:", dict(zip(le.classes_, le.transform(le.classes_))))

(102, 768)
(102, 768)
Label mapping: {'negative': np.int64(0), 'neutral': np.int64(1), 'positive': np.int64(2)}

In [48]:
#training dan evaluasi
clf = LogisticRegression(max_iter=1000)
clf.fit(train_embedding, train_labels)
print("Training selesai!")

valid_preds = clf.predict(valid_embeddings)
print("\n=== HASIL VALIDASI ===")
print(classification_report(valid_labels, valid_preds, target_names=le.classes_))

# Evaluasi Test ← hasil akhir
test_preds = clf.predict(test_embeddings)
print("\n=== HASIL TEST ===")
print(classification_report(test_labels, test_preds, target_names=le.classes_))

Training selesai!

=== HASIL VALIDASI ===
              precision    recall  f1-score   support

    negative       0.82      0.91      0.86        34
     neutral       0.91      0.85      0.88        34
    positive       0.88      0.82      0.85        34

    accuracy                           0.86       102
   macro avg       0.87      0.86      0.86       102
weighted avg       0.87      0.86      0.86       102


=== HASIL TEST ===
              precision    recall  f1-score   support

    negative       0.68      1.00      0.81        34
     neutral       1.00      0.47      0.64        34
    positive       0.69      0.74      0.71        34

    accuracy                           0.74       102
   macro avg       0.79      0.74      0.72       102
weighted avg       0.79      0.74      0.72       102

In [49]:
#sample prediksi
def predict(text):
    emb = embedding(text).reshape(1, -1)
    pred = clf.predict(emb)
    proba = clf.predict_proba(emb).max()
    label = le.inverse_transform(pred)[0]
    print(f"Teks    : {text}")
    print(f"Prediksi: {label}")
    print("\n")

# Test beberapa contoh
predict("Produk ini sangat bagus dan recommended!")
predict("Pelayanan sangat lambat dan mengecewakan")
predict("nolimit adalah sebuah perusahaan")

Teks    : Produk ini sangat bagus dan recommended!
Prediksi: positive


Teks    : Pelayanan sangat lambat dan mengecewakan
Prediksi: neutral


Teks    : nolimit adalah sebuah perusahaan
Prediksi: neutral

# **SAVE SAMPLE DATA**

In [50]:
import os
os.makedirs('data', exist_ok=True)

df_train.groupby('label').head(100).reset_index(drop=True).to_csv('data/sample_train.csv', index=False)
df_valid.groupby('label').head(100).reset_index(drop=True).to_csv('data/sample_valid.csv', index=False)
df_test.groupby('label').head(100).reset_index(drop=True).to_csv('data/sample_test.csv', index=False)

print("Semua sample berhasil disimpan!")
print(f"Train : {len(df_train.groupby('label').head(34))} baris")
print(f"Valid : {len(df_valid.groupby('label').head(34))} baris")
print(f"Test  : {len(df_test.groupby('label').head(34))} baris")

Semua sample berhasil disimpan!
Train : 102 baris
Valid : 102 baris
Test  : 102 baris